package model.enumeration;

public enum Escolaridade {
    FUNDAMENTAL_INCOMPLETO,
    FUNDAMENTAL_COMPLETO,
    MEDIO_INCOMPLETO,
    MEDIO_COMPLETO,
    SUPERIOR_INCOMPLETO,
    SUPERIOR_COMPLETO,
    MESTRADO_INCOMPLETO,
    MESTRADO_COMPLETO,
    DOUTORADO_INCOMPLETO,
    DOUTORADO_COMPLETO
}
